server:
  port: 8769

spring:
  profiles: peer2
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    registerWithEureka: false
    fetchRegistry: false
